const ERROR_CODES = {
  USER_CREATE_FAILED: "USER_CREATE_FAILED",
  USER_NOT_FOUND: "USER_NOT_FOUND",
  AUTH_SIGN_UP_FAILED: "AUTH_SIGN_UP_FAILED",
  AUTH_UNAUTHORIZED: "AUTH_UNAUTHORIZED",
} as const;

export { ERROR_CODES };

export type ErrorCodes = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
